# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
      env: 
        REACT_APP_API_KEY: ${{ secrets.REACT_APP_API_KEY }}
        REACT_APP_AUTH_DOMAIN: ${{ secrets.REACT_APP_AUTH_DOMAIN }}
        REACT_APP_DATABASE_URL: ${{ secrets.REACT_APP_DATABASE_URL }}
        REACT_APP_PROJECT_ID: ${{ secrets.REACT_APP_PROJECT_ID }}
        REACT_APP_STORAGE_BUCKET: ${{ secrets.REACT_APP_STORAGE_BUCKET }}
        REACT_APP_MESSAGING_SENDER_ID: ${{ secrets.REACT_APP_MESSAGING_SENDER_ID }}
        REACT_APP_APP_ID : ${{ secrets.REACT_APP_APP_ID }}
    - run: echo ${{github.ref}}
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
  release:
    needs: build
    runs-on: ubuntu-latest
    name: deploy
    steps:
    - uses: actions/checkout@v2.1.0
      with:
        fetch-depth: 2
    - name: Deploy to OVH
      uses: SamKirkland/FTP-Deploy-Action@3.1.1
      with:
        ftp-server: sftp://ssh.cluster023.hosting.ovh.net/
        ftp-username: ${{ secrets.OVH_HOSTING_USER }}
        ftp-password: ${{ secrets.OVH_HOSTING_PASSWORD }}
        local-dir: build
